"""initial schema

Revision ID: 710a97dc14ab
Revises: 
Create Date: 2026-08-26 21:08:14.254905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '710a97dc14ab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('published_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('collected_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('engagement_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('llm_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_table('cost_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('finished_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('failures', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_date')
    )
    op.create_table('digest',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('generated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('trend_summary', sa.Text(), nullable=True),
    sa.Column('email_sent_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('email_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['run_date'], ['pipeline_run.run_date'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_date')
    )
    op.create_table('digest_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('digest_id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('final_score', sa.Numeric(), nullable=False),
    sa.Column('is_diversity_pick', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ),
    sa.ForeignKeyConstraint(['digest_id'], ['digest.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('digest_id', 'content_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('digest_item')
    op.drop_table('digest')
    op.drop_table('pipeline_run')
    op.drop_table('cost_ledger')
    op.drop_table('content')
    # ### end Alembic commands ###
